# Generated by Django 2.1 on 2018-12-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivioapp', '0002_auto_20181208_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
