# Generated by Django 2.1 on 2019-01-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivioapp', '0003_auto_20181208_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
