# Generated by Django 2.1 on 2019-01-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivioapp', '0004_customuser_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
